///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ZangConnectWebEx
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The cal recording.
    /// </summary>
    [TestModule("573bc2c3-9969-45be-ac3d-09d5c8a614c7", ModuleType.Recording, 1)]
    public partial class cal : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ZangConnectWebExRepository repository.
        /// </summary>
        public static ZangConnectWebExRepository repo = ZangConnectWebExRepository.Instance;

        static cal instance = new cal();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public cal()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static cal Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://outlook.office.com/owa/?path=/calendar/view/Day' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://outlook.office.com/owa/?path=/calendar/view/Day", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(1));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=286,Y=167}.", new RecordItemIndex(2));
            Mouse.MoveTo(286, 167);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(3));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=342,Y=260}.", new RecordItemIndex(4));
            Mouse.MoveTo(342, 260);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test1114'.", new RecordItemIndex(5));
            Keyboard.Press("test1114");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=419,Y=382}.", new RecordItemIndex(6));
            Mouse.MoveTo(419, 382);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down at {X=457,Y=383}.", new RecordItemIndex(7));
            Mouse.MoveTo(457, 383);
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move at {X=457,Y=383}.", new RecordItemIndex(8));
            Mouse.MoveTo(457, 383);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up at {X=300,Y=369}.", new RecordItemIndex(9));
            Mouse.MoveTo(300, 369);
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back} 4:00 PM{Tab}{Tab}{Tab}4:30 PM'.", new RecordItemIndex(10));
            Keyboard.Press("{Back} 4:00 PM{Tab}{Tab}{Tab}4:30 PM");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=294,Y=666}.", new RecordItemIndex(11));
            Mouse.MoveTo(294, 666);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1146,Y=330}.", new RecordItemIndex(12));
            Mouse.MoveTo(1146, 330);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1080,Y=378}.", new RecordItemIndex(13));
            Mouse.MoveTo(1080, 378);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1144,Y=364}.", new RecordItemIndex(14));
            Mouse.MoveTo(1144, 364);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=989,Y=416}.", new RecordItemIndex(15));
            Mouse.MoveTo(989, 416);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1032,Y=476}.", new RecordItemIndex(16));
            Mouse.MoveTo(1032, 476);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1111a'.", new RecordItemIndex(17));
            Keyboard.Press("1111a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1019,Y=535}.", new RecordItemIndex(18));
            Mouse.MoveTo(1019, 535);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(19));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=115,Y=158}.", new RecordItemIndex(20));
            Mouse.MoveTo(115, 158);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(21));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContactManagerMatheesanmAtesnaCom.DivTagNR4.Test1114' at 33;8.", repo.ContactManagerMatheesanmAtesnaCom.DivTagNR4.Test1114Info, new RecordItemIndex(22));
            repo.ContactManagerMatheesanmAtesnaCom.DivTagNR4.Test1114.Click("33;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(23));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1626,Y=664}.", new RecordItemIndex(24));
            Mouse.MoveTo(1626, 664);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(25));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContactManagerMatheesanmAtesnaCom.WexButtonStart' at 77;16.", repo.ContactManagerMatheesanmAtesnaCom.WexButtonStartInfo, new RecordItemIndex(26));
            repo.ContactManagerMatheesanmAtesnaCom.WexButtonStart.Click("77;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(27));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(28));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CiscoWebExMeetingCenter.EndMeeting' at 70;13.", repo.CiscoWebExMeetingCenter.EndMeetingInfo, new RecordItemIndex(29));
            repo.CiscoWebExMeetingCenter.EndMeeting.Click("70;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(30));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EndMeeting.EndMeeting' at 113;17.", repo.EndMeeting.EndMeetingInfo, new RecordItemIndex(31));
            repo.EndMeeting.EndMeeting.Click("113;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(32));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContactManagerMatheesanmAtesnaCom.SomeTdTag' at 690;27.", repo.ContactManagerMatheesanmAtesnaCom.SomeTdTagInfo, new RecordItemIndex(33));
            repo.ContactManagerMatheesanmAtesnaCom.SomeTdTag.Click("690;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+W' Press.", new RecordItemIndex(34));
            Keyboard.Press(System.Windows.Forms.Keys.W | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+W' Press.", new RecordItemIndex(35));
            Keyboard.Press(System.Windows.Forms.Keys.W | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
