///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ZangConnectWebEx
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateMeeting1 recording.
    /// </summary>
    [TestModule("0a1981df-2e01-4348-9939-cb0cebe1b7cd", ModuleType.Recording, 1)]
    public partial class CreateMeeting1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ZangConnectWebExRepository repository.
        /// </summary>
        public static ZangConnectWebExRepository repo = ZangConnectWebExRepository.Instance;

        static CreateMeeting1 instance = new CreateMeeting1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateMeeting1()
        {
            applyTemplateonExtensionLocation = "1860;150";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateMeeting1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _applyTemplateonExtensionLocation;

        /// <summary>
        /// Gets or sets the value of variable applyTemplateonExtensionLocation.
        /// </summary>
        [TestVariable("c9673ceb-e4b8-4370-97a8-6e78a5a0b5eb")]
        public string applyTemplateonExtensionLocation
        {
            get { return _applyTemplateonExtensionLocation; }
            set { _applyTemplateonExtensionLocation = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ZangConnectGoogleChrome.ZangConnectForWebEx' at 17;15.", repo.ZangConnectGoogleChrome.ZangConnectForWebExInfo, new RecordItemIndex(0));
            repo.ZangConnectGoogleChrome.ZangConnectForWebEx.Click("17;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1860,Y=150}.", new RecordItemIndex(1));
            Mouse.MoveTo(1860, 150);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1860,Y=180}.", new RecordItemIndex(2));
            Mouse.MoveTo(1860, 180);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1860,Y=180}.", new RecordItemIndex(3));
            Mouse.MoveTo(1860, 180);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}2'.", new RecordItemIndex(4));
            Keyboard.Press("{Back}2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1710,Y=260}.", new RecordItemIndex(5));
            Mouse.MoveTo(1710, 260);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1710,Y=295}.", new RecordItemIndex(6));
            Mouse.MoveTo(1710, 295);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1710,Y=315}.", new RecordItemIndex(7));
            Mouse.MoveTo(1710, 315);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1111a'.", new RecordItemIndex(8));
            Keyboard.Press("1111a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1710,Y=355}.", new RecordItemIndex(9));
            Mouse.MoveTo(1710, 355);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 12s.", new RecordItemIndex(10));
            Delay.Duration(12000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'CiscoWebExMeetingCenter.WebExMeetingHash111'.", repo.CiscoWebExMeetingCenter.WebExMeetingHash111Info, new RecordItemIndex(11));
            Validate.Attribute(repo.CiscoWebExMeetingCenter.WebExMeetingHash111Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='WebEx Meeting #112') on item 'CiscoWebExMeetingCenter.WebExMeetingHash111'.", repo.CiscoWebExMeetingCenter.WebExMeetingHash111Info, new RecordItemIndex(12));
            Validate.Attribute(repo.CiscoWebExMeetingCenter.WebExMeetingHash111Info, "Text", "WebEx Meeting #112");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CiscoWebExMeetingCenter.EndMeeting' at 54;17.", repo.CiscoWebExMeetingCenter.EndMeetingInfo, new RecordItemIndex(13));
            repo.CiscoWebExMeetingCenter.EndMeeting.Click("54;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EndMeeting.EndMeeting' at 93;21.", repo.EndMeeting.EndMeetingInfo, new RecordItemIndex(14));
            repo.EndMeeting.EndMeeting.Click("93;21");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
