///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ZangConnectWebEx
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The googleCalendarValidation recording.
    /// </summary>
    [TestModule("b1359b62-1748-45a9-a2e2-c589ff80977e", ModuleType.Recording, 1)]
    public partial class googleCalendarValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ZangConnectWebExRepository repository.
        /// </summary>
        public static ZangConnectWebExRepository repo = ZangConnectWebExRepository.Instance;

        static googleCalendarValidation instance = new googleCalendarValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public googleCalendarValidation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static googleCalendarValidation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://calendar.google.com/calendar/r' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://calendar.google.com/calendar/r", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EsnaComCalendarWeekOfOctober2.Gw6Zhc' at 6;10.", repo.EsnaComCalendarWeekOfOctober2.Gw6ZhcInfo, new RecordItemIndex(1));
            repo.EsnaComCalendarWeekOfOctober2.Gw6Zhc.Click("6;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EsnaComCalendarWeekOfOctober2.Webex0addtext' at 63;7.", repo.EsnaComCalendarWeekOfOctober2.Webex0addtextInfo, new RecordItemIndex(2));
            repo.EsnaComCalendarWeekOfOctober2.Webex0addtext.Click("63;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EsnaComCalendarWeekOfOctober2' at 1142;118.", repo.EsnaComCalendarWeekOfOctober2.SelfInfo, new RecordItemIndex(3));
            repo.EsnaComCalendarWeekOfOctober2.Self.Click("1142;118");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 80;25.", repo.Dropdown.SelfInfo, new RecordItemIndex(4));
            repo.Dropdown.Self.Click("80;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EsnaComCalendarWeekOfOctober2' at 995;237.", repo.EsnaComCalendarWeekOfOctober2.SelfInfo, new RecordItemIndex(5));
            repo.EsnaComCalendarWeekOfOctober2.Self.Click("995;237");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 58;27.", repo.Dropdown.SelfInfo, new RecordItemIndex(6));
            repo.Dropdown.Self.Click("58;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EsnaComCalendarWeekOfOctober2' at 980;281.", repo.EsnaComCalendarWeekOfOctober2.SelfInfo, new RecordItemIndex(7));
            repo.EsnaComCalendarWeekOfOctober2.Self.Click("980;281");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 52;28.", repo.Dropdown.SelfInfo, new RecordItemIndex(8));
            repo.Dropdown.Self.Click("52;28");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EsnaComCalendarWeekOfOctober2' at 976;355.", repo.EsnaComCalendarWeekOfOctober2.SelfInfo, new RecordItemIndex(9));
            repo.EsnaComCalendarWeekOfOctober2.Self.Click("976;355");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 58;7.", repo.Dropdown.SelfInfo, new RecordItemIndex(10));
            repo.Dropdown.Self.Click("58;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EsnaComCalendarWeekOfOctober2' at 928;319.", repo.EsnaComCalendarWeekOfOctober2.SelfInfo, new RecordItemIndex(11));
            repo.EsnaComCalendarWeekOfOctober2.Self.Click("928;319");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EsnaComCalendarWeekOfOctober2' at 950;577.", repo.EsnaComCalendarWeekOfOctober2.SelfInfo, new RecordItemIndex(12));
            repo.EsnaComCalendarWeekOfOctober2.Self.Click("950;577");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(13));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EsnaComCalendarWeekOfOctober2.Webex0start' at Center.", repo.EsnaComCalendarWeekOfOctober2.Webex0startInfo, new RecordItemIndex(14));
            repo.EsnaComCalendarWeekOfOctober2.Webex0start.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(15));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Atmgr.Skip' at 18;14.", repo.Atmgr.SkipInfo, new RecordItemIndex(16));
            repo.Atmgr.Skip.Click("18;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Google Calendar') on item 'CiscoWebExMeetingCenter.WebExMeetingHash111'.", repo.CiscoWebExMeetingCenter.WebExMeetingHash111Info, new RecordItemIndex(17));
            Validate.Attribute(repo.CiscoWebExMeetingCenter.WebExMeetingHash111Info, "Text", "Google Calendar");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CiscoWebExMeetingCenter.EndMeeting' at 75;17.", repo.CiscoWebExMeetingCenter.EndMeetingInfo, new RecordItemIndex(18));
            repo.CiscoWebExMeetingCenter.EndMeeting.Click("75;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EndMeeting.EndMeeting' at 101;24.", repo.EndMeeting.EndMeetingInfo, new RecordItemIndex(19));
            repo.EndMeeting.EndMeeting.Click("101;24");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
