///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ZangConnectWebEx
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoogleCard recording.
    /// </summary>
    [TestModule("9aa645ae-5798-439e-a522-145baa9e6729", ModuleType.Recording, 1)]
    public partial class GoogleCard : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ZangConnectWebExRepository repository.
        /// </summary>
        public static ZangConnectWebExRepository repo = ZangConnectWebExRepository.Instance;

        static GoogleCard instance = new GoogleCard();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoogleCard()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoogleCard Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://mail.google.com/mail/u/0/#contacts' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://mail.google.com/mail/u/0/#contacts", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 15s.", new RecordItemIndex(1));
            Delay.Duration(15000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ContactManagerMatheesanmAtesnaCom1.EsnaTech' at Center.", repo.ContactManagerMatheesanmAtesnaCom1.EsnaTechInfo, new RecordItemIndex(2));
            repo.ContactManagerMatheesanmAtesnaCom1.EsnaTech.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=618,Y=528}.", new RecordItemIndex(4));
            Mouse.MoveTo(618, 528);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1077,Y=282}.", new RecordItemIndex(6));
            Mouse.MoveTo(1077, 282);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}'.", new RecordItemIndex(7));
            Keyboard.Press("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '3'.", new RecordItemIndex(8));
            Keyboard.Press("3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1007,Y=358}.", new RecordItemIndex(9));
            Mouse.MoveTo(1007, 358);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(10));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 24;29.", repo.Dropdown.SelfInfo, new RecordItemIndex(11));
            repo.Dropdown.Self.Click("24;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1031,Y=396}.", new RecordItemIndex(12));
            Mouse.MoveTo(1031, 396);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 97;11.", repo.Dropdown.SelfInfo, new RecordItemIndex(13));
            repo.Dropdown.Self.Click("97;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=953,Y=535}.", new RecordItemIndex(14));
            Mouse.MoveTo(953, 535);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1111a'.", new RecordItemIndex(15));
            Keyboard.Press("1111a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=956,Y=574}.", new RecordItemIndex(16));
            Mouse.MoveTo(956, 574);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(17));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Atmgr.Skip' at 14;14.", repo.Atmgr.SkipInfo, new RecordItemIndex(18));
            repo.Atmgr.Skip.Click("14;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='WebEx Meeting #113') on item 'CiscoWebExMeetingCenter.WebExMeetingHash111'.", repo.CiscoWebExMeetingCenter.WebExMeetingHash111Info, new RecordItemIndex(19));
            Validate.Attribute(repo.CiscoWebExMeetingCenter.WebExMeetingHash111Info, "Text", "WebEx Meeting #113");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CiscoWebExMeetingCenter.InviteAndRemindOthersToJoin' at 84;20.", repo.CiscoWebExMeetingCenter.InviteAndRemindOthersToJoinInfo, new RecordItemIndex(20));
            repo.CiscoWebExMeetingCenter.InviteAndRemindOthersToJoin.Click("84;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='esnatechqc@gmail.com') on item 'Atmgr.EsnatechqcAtgmailCom'.", repo.Atmgr.EsnatechqcAtgmailComInfo, new RecordItemIndex(21));
            Validate.Attribute(repo.Atmgr.EsnatechqcAtgmailComInfo, "Text", "esnatechqc@gmail.com");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Atmgr.Close' at 10;10.", repo.Atmgr.CloseInfo, new RecordItemIndex(22));
            repo.Atmgr.Close.Click("10;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CiscoWebExMeetingCenter.EndMeeting' at 73;14.", repo.CiscoWebExMeetingCenter.EndMeetingInfo, new RecordItemIndex(23));
            repo.CiscoWebExMeetingCenter.EndMeeting.Click("73;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EndMeeting.EndMeeting' at 98;24.", repo.EndMeeting.EndMeetingInfo, new RecordItemIndex(24));
            repo.EndMeeting.EndMeeting.Click("98;24");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
