///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ZangConnectWebEx
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The o365Mail recording.
    /// </summary>
    [TestModule("dac91092-ea48-48b9-acfc-35f2f35fc1fe", ModuleType.Recording, 1)]
    public partial class o365Mail : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ZangConnectWebExRepository repository.
        /// </summary>
        public static ZangConnectWebExRepository repo = ZangConnectWebExRepository.Instance;

        static o365Mail instance = new o365Mail();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public o365Mail()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static o365Mail Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://outlook.office.com/owa' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://outlook.office.com/owa", "Chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(1));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=313,Y=161}.", new RecordItemIndex(2));
            Mouse.MoveTo(313, 161);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(3));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'superuser@esnatech.onmicrosoft.com'.", new RecordItemIndex(4));
            Keyboard.Press("superuser@esnatech.onmicrosoft.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=670,Y=325}.", new RecordItemIndex(6));
            Mouse.MoveTo(670, 325);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test1112'.", new RecordItemIndex(8));
            Keyboard.Press("test1112");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(9));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=679,Y=162}.", new RecordItemIndex(10));
            Mouse.MoveTo(679, 162);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(11));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=61,Y=308}.", new RecordItemIndex(12));
            Mouse.MoveTo(61, 308);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(13));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move at {X=743,Y=313}.", new RecordItemIndex(14));
            Mouse.MoveTo(743, 313);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(15));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=801,Y=458}.", new RecordItemIndex(16));
            Mouse.MoveTo(801, 458);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(17));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=999,Y=354}.", new RecordItemIndex(18));
            Mouse.MoveTo(999, 354);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=999,Y=422}.", new RecordItemIndex(19));
            Mouse.MoveTo(999, 422);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=954,Y=352}.", new RecordItemIndex(20));
            Mouse.MoveTo(954, 352);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=954,Y=378}.", new RecordItemIndex(21));
            Mouse.MoveTo(954, 378);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=958,Y=425}.", new RecordItemIndex(22));
            Mouse.MoveTo(958, 425);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1111a'.", new RecordItemIndex(23));
            Keyboard.Press("1111a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1016,Y=469}.", new RecordItemIndex(24));
            Mouse.MoveTo(1016, 469);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(25));
            Delay.Duration(10000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContactManagerMatheesanmAtesnaCom.BtnJoinRoom' at 148;18.", repo.ContactManagerMatheesanmAtesnaCom.BtnJoinRoomInfo, new RecordItemIndex(26));
            //repo.ContactManagerMatheesanmAtesnaCom.BtnJoinRoom.Click("148;18");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(27));
            Delay.Duration(2000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Atmgr.Skip' at 17;12.", repo.Atmgr.SkipInfo, new RecordItemIndex(28));
            //repo.Atmgr.Skip.Click("17;12");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(29));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CiscoWebExMeetingCenter.InviteAndRemindOthersToJoin' at 105;10.", repo.CiscoWebExMeetingCenter.InviteAndRemindOthersToJoinInfo, new RecordItemIndex(30));
            repo.CiscoWebExMeetingCenter.InviteAndRemindOthersToJoin.Click("105;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1082,Y=387}.", new RecordItemIndex(31));
            Mouse.MoveTo(1082, 387);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=67,Y=191,Width=177,Height=25}) on item 'Atmgr.Atmgr'.", repo.Atmgr.AtmgrInfo, new RecordItemIndex(32));
            Validate.ContainsImage(repo.Atmgr.AtmgrInfo, Atmgr_Screenshot1, Atmgr_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1099,Y=329}.", new RecordItemIndex(33));
            Mouse.MoveTo(1099, 329);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CiscoWebExMeetingCenter.EndMeeting' at 68;16.", repo.CiscoWebExMeetingCenter.EndMeetingInfo, new RecordItemIndex(34));
            repo.CiscoWebExMeetingCenter.EndMeeting.Click("68;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EndMeeting.EndMeeting' at 124;16.", repo.EndMeeting.EndMeetingInfo, new RecordItemIndex(35));
            repo.EndMeeting.EndMeeting.Click("124;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(36));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EsnaTechnologiesIncWebExEnterpriseS.AddressAndSearchBar' at 90;78.", repo.EsnaTechnologiesIncWebExEnterpriseS.AddressAndSearchBarInfo, new RecordItemIndex(37));
            repo.EsnaTechnologiesIncWebExEnterpriseS.AddressAndSearchBar.Click("90;78");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+W' Press.", new RecordItemIndex(38));
            Keyboard.Press(System.Windows.Forms.Keys.W | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+W' Press.", new RecordItemIndex(39));
            Keyboard.Press(System.Windows.Forms.Keys.W | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage Atmgr_Screenshot1
        { get { return repo.Atmgr.AtmgrInfo.GetScreenshot1(new Rectangle(67, 191, 177, 25)); } }

        Imaging.FindOptions Atmgr_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
