///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ZangConnectWebEx
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SalesforceMeeting recording.
    /// </summary>
    [TestModule("7080c313-e8b8-44cd-bf75-5954bcd62996", ModuleType.Recording, 1)]
    public partial class SalesforceMeeting : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ZangConnectWebExRepository repository.
        /// </summary>
        public static ZangConnectWebExRepository repo = ZangConnectWebExRepository.Instance;

        static SalesforceMeeting instance = new SalesforceMeeting();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SalesforceMeeting()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SalesforceMeeting Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://na88.salesforce.com/home/home.jsp?tsid=02ui0000000eIX4' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://na88.salesforce.com/home/home.jsp?tsid=02ui0000000eIX4", "Chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginSalesforce.Username' at 109;29.", repo.LoginSalesforce.UsernameInfo, new RecordItemIndex(1));
            //repo.LoginSalesforce.Username.Click("109;29");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'arnoe@esna.com{Tab}EsnaAvaya09' with focus on 'LoginSalesforce.Username'.", repo.LoginSalesforce.UsernameInfo, new RecordItemIndex(2));
            //repo.LoginSalesforce.Username.PressKeys("arnoe@esna.com{Tab}EsnaAvaya09");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(3));
            //Keyboard.Press("{Return}");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AllowAccessSalesforce.NewEvent' at 23;15.", repo.AllowAccessSalesforce.NewEventInfo, new RecordItemIndex(4));
            repo.AllowAccessSalesforce.NewEvent.Click("23;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AllowAccessSalesforce.Wex0B7Cr1' at 51;15.", repo.AllowAccessSalesforce.Wex0B7Cr1Info, new RecordItemIndex(5));
            repo.AllowAccessSalesforce.Wex0B7Cr1.Click("51;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AllowAccessSalesforce' at 1139;116.", repo.AllowAccessSalesforce.SelfInfo, new RecordItemIndex(6));
            repo.AllowAccessSalesforce.Self.Click("1139;116");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 137;86.", repo.Dropdown.SelfInfo, new RecordItemIndex(7));
            repo.Dropdown.Self.Click("137;86");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AllowAccessSalesforce' at 988;284.", repo.AllowAccessSalesforce.SelfInfo, new RecordItemIndex(8));
            repo.AllowAccessSalesforce.Self.Click("988;284");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 69;30.", repo.Dropdown.SelfInfo, new RecordItemIndex(9));
            repo.Dropdown.Self.Click("69;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AllowAccessSalesforce' at 961;396.", repo.AllowAccessSalesforce.SelfInfo, new RecordItemIndex(10));
            repo.AllowAccessSalesforce.Self.Click("961;396");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1111a'.", new RecordItemIndex(11));
            Keyboard.Press("1111a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AllowAccessSalesforce' at 962;438.", repo.AllowAccessSalesforce.SelfInfo, new RecordItemIndex(12));
            repo.AllowAccessSalesforce.Self.Click("962;438");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(13));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AllowAccessSalesforce.Wex0B7Md1' at 33;12.", repo.AllowAccessSalesforce.Wex0B7Md1Info, new RecordItemIndex(14));
            repo.AllowAccessSalesforce.Wex0B7Md1.Click("33;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(15));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AllowAccessSalesforce' at 1136;200.", repo.AllowAccessSalesforce.SelfInfo, new RecordItemIndex(16));
            repo.AllowAccessSalesforce.Self.Click("1136;200");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 113;72.", repo.Dropdown.SelfInfo, new RecordItemIndex(17));
            repo.Dropdown.Self.Click("113;72");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AllowAccessSalesforce' at 980;369.", repo.AllowAccessSalesforce.SelfInfo, new RecordItemIndex(18));
            repo.AllowAccessSalesforce.Self.Click("980;369");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(19));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AllowAccessSalesforce.Evt5' at 71;8.", repo.AllowAccessSalesforce.Evt5Info, new RecordItemIndex(20));
            repo.AllowAccessSalesforce.Evt5.Click("71;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test1115' with focus on 'AllowAccessSalesforce.Evt5'.", repo.AllowAccessSalesforce.Evt5Info, new RecordItemIndex(21));
            repo.AllowAccessSalesforce.Evt5.PressKeys("test1115");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AllowAccessSalesforce.Save' at 30;7.", repo.AllowAccessSalesforce.SaveInfo, new RecordItemIndex(22));
            repo.AllowAccessSalesforce.Save.Click("30;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='test1115') on item 'ContactManagerMatheesanmAtesnaCom1.Test1115'.", repo.ContactManagerMatheesanmAtesnaCom1.Test1115Info, new RecordItemIndex(23));
            Validate.Attribute(repo.ContactManagerMatheesanmAtesnaCom1.Test1115Info, "InnerText", "test1115");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SalesforceDeveloperEditionGoogle.ZangConnectForWebEx' at 17;17.", repo.SalesforceDeveloperEditionGoogle.ZangConnectForWebExInfo, new RecordItemIndex(24));
            repo.SalesforceDeveloperEditionGoogle.ZangConnectForWebEx.Click("17;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=74,Y=365,Width=64,Height=23}) on item 'Chrome'.", repo.Chrome.SelfInfo, new RecordItemIndex(25));
            Validate.ContainsImage(repo.Chrome.SelfInfo, Chrome_Screenshot1, Chrome_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AllowAccessSalesforce.UserNavButton' at 125;15.", repo.AllowAccessSalesforce.UserNavButtonInfo, new RecordItemIndex(26));
            repo.AllowAccessSalesforce.UserNavButton.Click("125;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AllowAccessSalesforce.Logout' at 37;6.", repo.AllowAccessSalesforce.LogoutInfo, new RecordItemIndex(27));
            repo.AllowAccessSalesforce.Logout.Click("37;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+W' Press.", new RecordItemIndex(28));
            Keyboard.Press(System.Windows.Forms.Keys.W | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+W' Press.", new RecordItemIndex(29));
            Keyboard.Press(System.Windows.Forms.Keys.W | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage Chrome_Screenshot1
        { get { return repo.Chrome.SelfInfo.GetScreenshot1(new Rectangle(74, 365, 64, 23)); } }

        Imaging.FindOptions Chrome_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
