///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ZangConnectWebEx
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SignInO365 recording.
    /// </summary>
    [TestModule("965e777a-c367-434b-8c54-51b712450e22", ModuleType.Recording, 1)]
    public partial class SignInO365 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ZangConnectWebExRepository repository.
        /// </summary>
        public static ZangConnectWebExRepository repo = ZangConnectWebExRepository.Instance;

        static SignInO365 instance = new SignInO365();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SignInO365()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SignInO365 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ZangConnect.ZangConnect' at 952;360.", repo.ZangConnect.ZangConnectInfo, new RecordItemIndex(0));
            repo.ZangConnect.ZangConnect.Click("952;360");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInToYourAccount.DivTagUseA' at 48;14.", repo.SignInToYourAccount.DivTagUseAInfo, new RecordItemIndex(1));
            repo.SignInToYourAccount.DivTagUseA.Click("48;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SignInToYourAccount.CredUseridInputtext' at 233;17.", repo.SignInToYourAccount.CredUseridInputtextInfo, new RecordItemIndex(3));
            repo.SignInToYourAccount.CredUseridInputtext.MoveTo("233;17");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SignInToYourAccount.CredUseridInputtext' at 241;9.", repo.SignInToYourAccount.CredUseridInputtextInfo, new RecordItemIndex(4));
            repo.SignInToYourAccount.CredUseridInputtext.MoveTo("241;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'SignInToYourAccount.BackgroundBackgroundImage' at 1342;346.", repo.SignInToYourAccount.BackgroundBackgroundImageInfo, new RecordItemIndex(5));
            repo.SignInToYourAccount.BackgroundBackgroundImage.MoveTo("1342;346");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'SignInToYourAccount.CredUseridInputtext'.", repo.SignInToYourAccount.CredUseridInputtextInfo, new RecordItemIndex(6));
            repo.SignInToYourAccount.CredUseridInputtext.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'bryand@esnatech.onmicrosoft.com' with focus on 'SignInToYourAccount.CredUseridInputtext'.", repo.SignInToYourAccount.CredUseridInputtextInfo, new RecordItemIndex(7));
            repo.SignInToYourAccount.CredUseridInputtext.PressKeys("bryand@esnatech.onmicrosoft.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'SignInToYourAccount.CredUseridInputtext'.", repo.SignInToYourAccount.CredUseridInputtextInfo, new RecordItemIndex(8));
            repo.SignInToYourAccount.CredUseridInputtext.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}'.", new RecordItemIndex(9));
            Keyboard.Press("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '!esnatech1234${Return}'.", new RecordItemIndex(10));
            Keyboard.Press("!esnatech1234${Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 7s.", new RecordItemIndex(11));
            Delay.Duration(7000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot5' with region {X=953,Y=91,Width=307,Height=24}) on item 'ZangConnect'.", repo.ZangConnect.SelfInfo, new RecordItemIndex(12));
            Validate.ContainsImage(repo.ZangConnect.SelfInfo, ZangConnect_Screenshot5, ZangConnect_Screenshot5_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        CompressedImage ZangConnect_Screenshot5
        { get { return repo.ZangConnect.SelfInfo.GetScreenshot5(new Rectangle(953, 91, 307, 24)); } }

        Imaging.FindOptions ZangConnect_Screenshot5_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
