///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ZangConnectWebEx
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SignInGoogle recording.
    /// </summary>
    [TestModule("0643f785-6a73-4840-9984-cba703945349", ModuleType.Recording, 1)]
    public partial class SignInGoogle : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ZangConnectWebExRepository repository.
        /// </summary>
        public static ZangConnectWebExRepository repo = ZangConnectWebExRepository.Instance;

        static SignInGoogle instance = new SignInGoogle();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SignInGoogle()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SignInGoogle Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ZangConnect' at 946;250.", repo.ZangConnect.SelfInfo, new RecordItemIndex(0));
            repo.ZangConnect.Self.Click("946;250");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInGoogleAccounts.UseAnotherAccount' at 12;10.", repo.SignInGoogleAccounts.UseAnotherAccountInfo, new RecordItemIndex(1));
            repo.SignInGoogleAccounts.UseAnotherAccount.Click("12;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SignInGoogleAccounts.IdentifierId' at 213;12.", repo.SignInGoogleAccounts.IdentifierIdInfo, new RecordItemIndex(2));
            repo.SignInGoogleAccounts.IdentifierId.MoveTo("213;12");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SignInGoogleAccounts.IdentifierId' at 221;4.", repo.SignInGoogleAccounts.IdentifierIdInfo, new RecordItemIndex(3));
            repo.SignInGoogleAccounts.IdentifierId.MoveTo("221;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'SignInGoogleAccounts.Path' at 165;198.", repo.SignInGoogleAccounts.PathInfo, new RecordItemIndex(4));
            repo.SignInGoogleAccounts.Path.MoveTo("165;198");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}'.", new RecordItemIndex(5));
            Keyboard.Press("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'matheesanm@esna.com{Return}' with focus on 'SignInGoogleAccounts.IdentifierId'.", repo.SignInGoogleAccounts.IdentifierIdInfo, new RecordItemIndex(6));
            repo.SignInGoogleAccounts.IdentifierId.PressKeys("matheesanm@esna.com{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'preveena2113!{Return}'.", new RecordItemIndex(8));
            Keyboard.Press("preveena2113!{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(9));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInGoogleAccounts.ALLOW' at 27;7.", repo.SignInGoogleAccounts.ALLOWInfo, new RecordItemIndex(10));
            repo.SignInGoogleAccounts.ALLOW.Click("27;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 7s.", new RecordItemIndex(11));
            Delay.Duration(7000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot3' with region {X=1025,Y=91,Width=173,Height=23}) on item 'ZangConnect.ZangConnect'.", repo.ZangConnect.ZangConnectInfo, new RecordItemIndex(12));
            Validate.ContainsImage(repo.ZangConnect.ZangConnectInfo, ZangConnect_Screenshot3, ZangConnect_Screenshot3_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        CompressedImage ZangConnect_Screenshot3
        { get { return repo.ZangConnect.ZangConnectInfo.GetScreenshot3(new Rectangle(1025, 91, 173, 23)); } }

        Imaging.FindOptions ZangConnect_Screenshot3_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
