///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ZangConnectWebEx
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ZangConnectWebExRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("b007516a-69b7-41e0-bd23-34204f58e5f7")]
    public partial class ZangConnectWebExRepository : RepoGenBaseFolder
    {
        static ZangConnectWebExRepository instance = new ZangConnectWebExRepository();
        ZangConnectWebExRepositoryFolders.ZangConnectAppFolder _zangconnect;
        ZangConnectWebExRepositoryFolders.SignInGoogleAccountsAppFolder _signingoogleaccounts;
        ZangConnectWebExRepositoryFolders.LoginSalesforceAppFolder _loginsalesforce;
        ZangConnectWebExRepositoryFolders.AllowAccessSalesforceAppFolder _allowaccesssalesforce;
        ZangConnectWebExRepositoryFolders.SignInToYourAccountAppFolder _signintoyouraccount;
        ZangConnectWebExRepositoryFolders.ZangConnectGoogleChromeAppFolder _zangconnectgooglechrome;
        ZangConnectWebExRepositoryFolders.ChromeAppFolder _chrome;
        ZangConnectWebExRepositoryFolders.DropdownAppFolder _dropdown;
        ZangConnectWebExRepositoryFolders.CiscoWebExMeetingCenterAppFolder _ciscowebexmeetingcenter;
        ZangConnectWebExRepositoryFolders.EndMeetingAppFolder _endmeeting;
        ZangConnectWebExRepositoryFolders.EsnaComCalendarWeekOfOctober2AppFolder _esnacomcalendarweekofoctober2;
        ZangConnectWebExRepositoryFolders.AtmgrAppFolder _atmgr;
        ZangConnectWebExRepositoryFolders.ContactManagerMatheesanmAtesnaComAppFolder _contactmanagermatheesanmatesnacom;
        ZangConnectWebExRepositoryFolders.ContactManagerMatheesanmAtesnaCom1AppFolder _contactmanagermatheesanmatesnacom1;

        /// <summary>
        /// Gets the singleton class instance representing the ZangConnectWebExRepository element repository.
        /// </summary>
        [RepositoryFolder("b007516a-69b7-41e0-bd23-34204f58e5f7")]
        public static ZangConnectWebExRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ZangConnectWebExRepository() 
            : base("ZangConnectWebExRepository", "/", null, 0, false, "b007516a-69b7-41e0-bd23-34204f58e5f7", ".\\RepositoryImages\\ZangConnectWebExRepositoryb007516a.rximgres")
        {
            _zangconnect = new ZangConnectWebExRepositoryFolders.ZangConnectAppFolder(this);
            _signingoogleaccounts = new ZangConnectWebExRepositoryFolders.SignInGoogleAccountsAppFolder(this);
            _loginsalesforce = new ZangConnectWebExRepositoryFolders.LoginSalesforceAppFolder(this);
            _allowaccesssalesforce = new ZangConnectWebExRepositoryFolders.AllowAccessSalesforceAppFolder(this);
            _signintoyouraccount = new ZangConnectWebExRepositoryFolders.SignInToYourAccountAppFolder(this);
            _zangconnectgooglechrome = new ZangConnectWebExRepositoryFolders.ZangConnectGoogleChromeAppFolder(this);
            _chrome = new ZangConnectWebExRepositoryFolders.ChromeAppFolder(this);
            _dropdown = new ZangConnectWebExRepositoryFolders.DropdownAppFolder(this);
            _ciscowebexmeetingcenter = new ZangConnectWebExRepositoryFolders.CiscoWebExMeetingCenterAppFolder(this);
            _endmeeting = new ZangConnectWebExRepositoryFolders.EndMeetingAppFolder(this);
            _esnacomcalendarweekofoctober2 = new ZangConnectWebExRepositoryFolders.EsnaComCalendarWeekOfOctober2AppFolder(this);
            _atmgr = new ZangConnectWebExRepositoryFolders.AtmgrAppFolder(this);
            _contactmanagermatheesanmatesnacom = new ZangConnectWebExRepositoryFolders.ContactManagerMatheesanmAtesnaComAppFolder(this);
            _contactmanagermatheesanmatesnacom1 = new ZangConnectWebExRepositoryFolders.ContactManagerMatheesanmAtesnaCom1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b007516a-69b7-41e0-bd23-34204f58e5f7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ZangConnect folder.
        /// </summary>
        [RepositoryFolder("7ead6e87-c274-4746-9f5c-623296cbe900")]
        public virtual ZangConnectWebExRepositoryFolders.ZangConnectAppFolder ZangConnect
        {
            get { return _zangconnect; }
        }

        /// <summary>
        /// The SignInGoogleAccounts folder.
        /// </summary>
        [RepositoryFolder("b17ca842-baa7-4408-979c-01fc62ba32e4")]
        public virtual ZangConnectWebExRepositoryFolders.SignInGoogleAccountsAppFolder SignInGoogleAccounts
        {
            get { return _signingoogleaccounts; }
        }

        /// <summary>
        /// The LoginSalesforce folder.
        /// </summary>
        [RepositoryFolder("591f8f02-c5f8-4120-96c0-ae5f6cc9f955")]
        public virtual ZangConnectWebExRepositoryFolders.LoginSalesforceAppFolder LoginSalesforce
        {
            get { return _loginsalesforce; }
        }

        /// <summary>
        /// The AllowAccessSalesforce folder.
        /// </summary>
        [RepositoryFolder("00f10c76-02f9-4eb1-bfc3-c721a370e610")]
        public virtual ZangConnectWebExRepositoryFolders.AllowAccessSalesforceAppFolder AllowAccessSalesforce
        {
            get { return _allowaccesssalesforce; }
        }

        /// <summary>
        /// The SignInToYourAccount folder.
        /// </summary>
        [RepositoryFolder("df1d1d54-7ee1-4b77-9c4e-529bbf3d9113")]
        public virtual ZangConnectWebExRepositoryFolders.SignInToYourAccountAppFolder SignInToYourAccount
        {
            get { return _signintoyouraccount; }
        }

        /// <summary>
        /// The ZangConnectGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("8d16435a-b141-4d20-9065-d6d559156dc8")]
        public virtual ZangConnectWebExRepositoryFolders.ZangConnectGoogleChromeAppFolder ZangConnectGoogleChrome
        {
            get { return _zangconnectgooglechrome; }
        }

        /// <summary>
        /// The Chrome folder.
        /// </summary>
        [RepositoryFolder("9c4c7428-8c47-4a17-b67a-eff7de12bd9a")]
        public virtual ZangConnectWebExRepositoryFolders.ChromeAppFolder Chrome
        {
            get { return _chrome; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("d6a7a029-e114-47e5-9070-c16335381b3d")]
        public virtual ZangConnectWebExRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }

        /// <summary>
        /// The CiscoWebExMeetingCenter folder.
        /// </summary>
        [RepositoryFolder("2cc40ca8-7d17-4fd1-b171-d884a32500d7")]
        public virtual ZangConnectWebExRepositoryFolders.CiscoWebExMeetingCenterAppFolder CiscoWebExMeetingCenter
        {
            get { return _ciscowebexmeetingcenter; }
        }

        /// <summary>
        /// The EndMeeting folder.
        /// </summary>
        [RepositoryFolder("ba8edcfe-6fd4-451a-8e57-258f7a459b50")]
        public virtual ZangConnectWebExRepositoryFolders.EndMeetingAppFolder EndMeeting
        {
            get { return _endmeeting; }
        }

        /// <summary>
        /// The EsnaComCalendarWeekOfOctober2 folder.
        /// </summary>
        [RepositoryFolder("9eda9743-21b8-44e4-ba40-ea522f435255")]
        public virtual ZangConnectWebExRepositoryFolders.EsnaComCalendarWeekOfOctober2AppFolder EsnaComCalendarWeekOfOctober2
        {
            get { return _esnacomcalendarweekofoctober2; }
        }

        /// <summary>
        /// The Atmgr folder.
        /// </summary>
        [RepositoryFolder("a8e1ec56-f657-48da-a99a-3ab7829a13a4")]
        public virtual ZangConnectWebExRepositoryFolders.AtmgrAppFolder Atmgr
        {
            get { return _atmgr; }
        }

        /// <summary>
        /// The ContactManagerMatheesanmAtesnaCom folder.
        /// </summary>
        [RepositoryFolder("edaff561-c490-4720-bb36-08ce2d71f26e")]
        public virtual ZangConnectWebExRepositoryFolders.ContactManagerMatheesanmAtesnaComAppFolder ContactManagerMatheesanmAtesnaCom
        {
            get { return _contactmanagermatheesanmatesnacom; }
        }

        /// <summary>
        /// The ContactManagerMatheesanmAtesnaCom1 folder.
        /// </summary>
        [RepositoryFolder("057df526-6445-4918-979c-b660250e3989")]
        public virtual ZangConnectWebExRepositoryFolders.ContactManagerMatheesanmAtesnaCom1AppFolder ContactManagerMatheesanmAtesnaCom1
        {
            get { return _contactmanagermatheesanmatesnacom1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class ZangConnectWebExRepositoryFolders
    {
        /// <summary>
        /// The ZangConnectAppFolder folder.
        /// </summary>
        [RepositoryFolder("7ead6e87-c274-4746-9f5c-623296cbe900")]
        public partial class ZangConnectAppFolder : RepoGenBaseFolder
        {
            SelfInfoClass _selfInfo;
            ZangConnectInfoClass _zangconnectInfo;

            /// <summary>
            /// Creates a new ZangConnect  folder.
            /// </summary>
            public ZangConnectAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ZangConnect", "/dom[@domain='hdhdfgbiafacojageghcplflcahlokji']", parentFolder, 30000, null, false, "7ead6e87-c274-4746-9f5c-623296cbe900", "")
            {
                _selfInfo = new SelfInfoClass(this);
                _zangconnectInfo = new ZangConnectInfoClass(this);
            }

            /// <summary>
            /// The SelfInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("7ead6e87-c274-4746-9f5c-623296cbe900")]
            public class SelfInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SelfInfoClass class constructor.
                /// </summary>
                public SelfInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Self", "", 0, null, "7ead6e87-c274-4746-9f5c-623296cbe900")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("8824495b-8048-4418-bb71-de821a19713b")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("8824495b-8048-4418-bb71-de821a19713b");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("8824495b-8048-4418-bb71-de821a19713b")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("8824495b-8048-4418-bb71-de821a19713b", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("42c3907e-b12d-4858-bb10-5d63edd0635e")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("42c3907e-b12d-4858-bb10-5d63edd0635e");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("42c3907e-b12d-4858-bb10-5d63edd0635e")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("42c3907e-b12d-4858-bb10-5d63edd0635e", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <returns>The Screenshot3 image.</returns>
                [RepositoryImage("61a605e8-814d-4b8d-b7e4-1107c0044f61")]
                public CompressedImage GetScreenshot3()
                {
                    return GetImage("61a605e8-814d-4b8d-b7e4-1107c0044f61");
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("61a605e8-814d-4b8d-b7e4-1107c0044f61")]
                public CompressedImage GetScreenshot3(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("61a605e8-814d-4b8d-b7e4-1107c0044f61", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <returns>The Screenshot4 image.</returns>
                [RepositoryImage("2d43abc0-d870-45ca-82c5-461c0118d01c")]
                public CompressedImage GetScreenshot4()
                {
                    return GetImage("2d43abc0-d870-45ca-82c5-461c0118d01c");
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("2d43abc0-d870-45ca-82c5-461c0118d01c")]
                public CompressedImage GetScreenshot4(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("2d43abc0-d870-45ca-82c5-461c0118d01c", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot5 item image.
                /// </summary>
                /// <returns>The Screenshot5 image.</returns>
                [RepositoryImage("361ce2b2-aa19-48dd-a92c-df01b143f921")]
                public CompressedImage GetScreenshot5()
                {
                    return GetImage("361ce2b2-aa19-48dd-a92c-df01b143f921");
                }

                /// <summary>
                /// Gets the Screenshot5 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("361ce2b2-aa19-48dd-a92c-df01b143f921")]
                public CompressedImage GetScreenshot5(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("361ce2b2-aa19-48dd-a92c-df01b143f921", cropRect);
                }
            }

            /// <summary>
            /// The ZangConnectInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("35f997fc-b404-4be4-bd7e-e52b3fd59ff0")]
            public class ZangConnectInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ZangConnectInfoClass class constructor.
                /// </summary>
                public ZangConnectInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ZangConnect", "", 30000, null, "35f997fc-b404-4be4-bd7e-e52b3fd59ff0")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("2582e4a4-8a19-45ba-a39d-47cf92e2da58")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("2582e4a4-8a19-45ba-a39d-47cf92e2da58");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("2582e4a4-8a19-45ba-a39d-47cf92e2da58")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("2582e4a4-8a19-45ba-a39d-47cf92e2da58", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("1d482536-d552-4e28-9667-5af3982ea11d")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("1d482536-d552-4e28-9667-5af3982ea11d");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("1d482536-d552-4e28-9667-5af3982ea11d")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("1d482536-d552-4e28-9667-5af3982ea11d", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <returns>The Screenshot3 image.</returns>
                [RepositoryImage("93b0f3f4-3530-4948-bcf9-165a4d10fc05")]
                public CompressedImage GetScreenshot3()
                {
                    return GetImage("93b0f3f4-3530-4948-bcf9-165a4d10fc05");
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("93b0f3f4-3530-4948-bcf9-165a4d10fc05")]
                public CompressedImage GetScreenshot3(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("93b0f3f4-3530-4948-bcf9-165a4d10fc05", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ead6e87-c274-4746-9f5c-623296cbe900")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ead6e87-c274-4746-9f5c-623296cbe900")]
            public virtual SelfInfoClass SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ZangConnect item.
            /// </summary>
            [RepositoryItem("35f997fc-b404-4be4-bd7e-e52b3fd59ff0")]
            public virtual Ranorex.WebDocument ZangConnect
            {
                get
                {
                    return _zangconnectInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The ZangConnect item info.
            /// </summary>
            [RepositoryItemInfo("35f997fc-b404-4be4-bd7e-e52b3fd59ff0")]
            public virtual ZangConnectInfoClass ZangConnectInfo
            {
                get
                {
                    return _zangconnectInfo;
                }
            }
        }

        /// <summary>
        /// The SignInGoogleAccountsAppFolder folder.
        /// </summary>
        [RepositoryFolder("b17ca842-baa7-4408-979c-01fc62ba32e4")]
        public partial class SignInGoogleAccountsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _useanotheraccountInfo;
            RepoItemInfo _identifieridInfo;
            RepoItemInfo _allowInfo;
            RepoItemInfo _pathInfo;

            /// <summary>
            /// Creates a new SignInGoogleAccounts  folder.
            /// </summary>
            public SignInGoogleAccountsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SignInGoogleAccounts", "/dom[@domain='accounts.google.com']", parentFolder, 30000, null, false, "b17ca842-baa7-4408-979c-01fc62ba32e4", "")
            {
                _useanotheraccountInfo = new RepoItemInfo(this, "UseAnotherAccount", ".//div[#'identifierLink']/?/?/p[@innertext='Use another account']", 30000, null, "0586fc2d-61cb-4e90-a0fe-d1dad232f677");
                _identifieridInfo = new RepoItemInfo(this, "IdentifierId", ".//input[#'identifierId']", 30000, null, "5f4fe2f5-7c18-4304-8d81-cb4e56133c0c");
                _allowInfo = new RepoItemInfo(this, "ALLOW", ".//div[#'submit_approve_access']/?/?/span[@innertext='ALLOW']", 30000, null, "4b4a9c56-f2d7-454b-bf19-b1799f2071ba");
                _pathInfo = new RepoItemInfo(this, "Path", ".//body[#'yDmH0d']/div[1]/?/?/tag[@tagname='svg']/tag[2]", 30000, null, "14537b5f-e84b-408e-88d7-315063d17092");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b17ca842-baa7-4408-979c-01fc62ba32e4")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b17ca842-baa7-4408-979c-01fc62ba32e4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UseAnotherAccount item.
            /// </summary>
            [RepositoryItem("0586fc2d-61cb-4e90-a0fe-d1dad232f677")]
            public virtual Ranorex.PTag UseAnotherAccount
            {
                get
                {
                    return _useanotheraccountInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The UseAnotherAccount item info.
            /// </summary>
            [RepositoryItemInfo("0586fc2d-61cb-4e90-a0fe-d1dad232f677")]
            public virtual RepoItemInfo UseAnotherAccountInfo
            {
                get
                {
                    return _useanotheraccountInfo;
                }
            }

            /// <summary>
            /// The IdentifierId item.
            /// </summary>
            [RepositoryItem("5f4fe2f5-7c18-4304-8d81-cb4e56133c0c")]
            public virtual Ranorex.InputTag IdentifierId
            {
                get
                {
                    return _identifieridInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The IdentifierId item info.
            /// </summary>
            [RepositoryItemInfo("5f4fe2f5-7c18-4304-8d81-cb4e56133c0c")]
            public virtual RepoItemInfo IdentifierIdInfo
            {
                get
                {
                    return _identifieridInfo;
                }
            }

            /// <summary>
            /// The ALLOW item.
            /// </summary>
            [RepositoryItem("4b4a9c56-f2d7-454b-bf19-b1799f2071ba")]
            public virtual Ranorex.SpanTag ALLOW
            {
                get
                {
                    return _allowInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ALLOW item info.
            /// </summary>
            [RepositoryItemInfo("4b4a9c56-f2d7-454b-bf19-b1799f2071ba")]
            public virtual RepoItemInfo ALLOWInfo
            {
                get
                {
                    return _allowInfo;
                }
            }

            /// <summary>
            /// The Path item.
            /// </summary>
            [RepositoryItem("14537b5f-e84b-408e-88d7-315063d17092")]
            public virtual Ranorex.WebElement Path
            {
                get
                {
                    return _pathInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Path item info.
            /// </summary>
            [RepositoryItemInfo("14537b5f-e84b-408e-88d7-315063d17092")]
            public virtual RepoItemInfo PathInfo
            {
                get
                {
                    return _pathInfo;
                }
            }
        }

        /// <summary>
        /// The LoginSalesforceAppFolder folder.
        /// </summary>
        [RepositoryFolder("591f8f02-c5f8-4120-96c0-ae5f6cc9f955")]
        public partial class LoginSalesforceAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;

            /// <summary>
            /// Creates a new LoginSalesforce  folder.
            /// </summary>
            public LoginSalesforceAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginSalesforce", "/dom[@domain='login.salesforce.com']", parentFolder, 30000, null, false, "591f8f02-c5f8-4120-96c0-ae5f6cc9f955", "")
            {
                _usernameInfo = new RepoItemInfo(this, "Username", ".//input[#'username']", 30000, null, "bb9bacfe-9faf-4034-b618-3b89ea623fed");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("591f8f02-c5f8-4120-96c0-ae5f6cc9f955")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("591f8f02-c5f8-4120-96c0-ae5f6cc9f955")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("bb9bacfe-9faf-4034-b618-3b89ea623fed")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("bb9bacfe-9faf-4034-b618-3b89ea623fed")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }
        }

        /// <summary>
        /// The AllowAccessSalesforceAppFolder folder.
        /// </summary>
        [RepositoryFolder("00f10c76-02f9-4eb1-bfc3-c721a370e610")]
        public partial class AllowAccessSalesforceAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _oaapproveInfo;

            /// <summary>
            /// Creates a new AllowAccessSalesforce  folder.
            /// </summary>
            public AllowAccessSalesforceAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AllowAccessSalesforce", "/dom[@domain='na88.salesforce.com']", parentFolder, 30000, null, false, "00f10c76-02f9-4eb1-bfc3-c721a370e610", "")
            {
                _oaapproveInfo = new RepoItemInfo(this, "Oaapprove", ".//input[#'oaapprove']", 30000, null, "0214ee74-b653-4c4f-a6cb-645bf91535b3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("00f10c76-02f9-4eb1-bfc3-c721a370e610")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("00f10c76-02f9-4eb1-bfc3-c721a370e610")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Oaapprove item.
            /// </summary>
            [RepositoryItem("0214ee74-b653-4c4f-a6cb-645bf91535b3")]
            public virtual Ranorex.InputTag Oaapprove
            {
                get
                {
                    return _oaapproveInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Oaapprove item info.
            /// </summary>
            [RepositoryItemInfo("0214ee74-b653-4c4f-a6cb-645bf91535b3")]
            public virtual RepoItemInfo OaapproveInfo
            {
                get
                {
                    return _oaapproveInfo;
                }
            }
        }

        /// <summary>
        /// The SignInToYourAccountAppFolder folder.
        /// </summary>
        [RepositoryFolder("df1d1d54-7ee1-4b77-9c4e-529bbf3d9113")]
        public partial class SignInToYourAccountAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _divtaguseaInfo;
            RepoItemInfo _creduseridinputtextInfo;
            RepoItemInfo _backgroundbackgroundimageInfo;

            /// <summary>
            /// Creates a new SignInToYourAccount  folder.
            /// </summary>
            public SignInToYourAccountAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SignInToYourAccount", "/dom[@domain='login.microsoftonline.com']", parentFolder, 30000, null, false, "df1d1d54-7ee1-4b77-9c4e-529bbf3d9113", "")
            {
                _divtaguseaInfo = new RepoItemInfo(this, "DivTagUseA", ".//table[#'use_another_account']//td/table/tbody/tr[2]/td[2]/div[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']", 30000, null, "ef7dcab6-91a8-475c-8984-ec5873748581");
                _creduseridinputtextInfo = new RepoItemInfo(this, "CredUseridInputtext", ".//input[#'cred_userid_inputtext']", 30000, null, "9c0d00b0-8ea2-47ff-a066-789f1df39303");
                _backgroundbackgroundimageInfo = new RepoItemInfo(this, "BackgroundBackgroundImage", ".//img[#'background_background_image']", 30000, null, "947b108b-23b3-4512-9af0-9a0a20a14fd3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("df1d1d54-7ee1-4b77-9c4e-529bbf3d9113")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("df1d1d54-7ee1-4b77-9c4e-529bbf3d9113")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DivTagUseA item.
            /// </summary>
            [RepositoryItem("ef7dcab6-91a8-475c-8984-ec5873748581")]
            public virtual Ranorex.DivTag DivTagUseA
            {
                get
                {
                    return _divtaguseaInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagUseA item info.
            /// </summary>
            [RepositoryItemInfo("ef7dcab6-91a8-475c-8984-ec5873748581")]
            public virtual RepoItemInfo DivTagUseAInfo
            {
                get
                {
                    return _divtaguseaInfo;
                }
            }

            /// <summary>
            /// The CredUseridInputtext item.
            /// </summary>
            [RepositoryItem("9c0d00b0-8ea2-47ff-a066-789f1df39303")]
            public virtual Ranorex.InputTag CredUseridInputtext
            {
                get
                {
                    return _creduseridinputtextInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CredUseridInputtext item info.
            /// </summary>
            [RepositoryItemInfo("9c0d00b0-8ea2-47ff-a066-789f1df39303")]
            public virtual RepoItemInfo CredUseridInputtextInfo
            {
                get
                {
                    return _creduseridinputtextInfo;
                }
            }

            /// <summary>
            /// The BackgroundBackgroundImage item.
            /// </summary>
            [RepositoryItem("947b108b-23b3-4512-9af0-9a0a20a14fd3")]
            public virtual Ranorex.ImgTag BackgroundBackgroundImage
            {
                get
                {
                    return _backgroundbackgroundimageInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The BackgroundBackgroundImage item info.
            /// </summary>
            [RepositoryItemInfo("947b108b-23b3-4512-9af0-9a0a20a14fd3")]
            public virtual RepoItemInfo BackgroundBackgroundImageInfo
            {
                get
                {
                    return _backgroundbackgroundimageInfo;
                }
            }
        }

        /// <summary>
        /// The ZangConnectGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("8d16435a-b141-4d20-9065-d6d559156dc8")]
        public partial class ZangConnectGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _zangconnectforwebexInfo;
            RepoItemInfo _zangconnectforwebex1Info;

            /// <summary>
            /// Creates a new ZangConnectGoogleChrome  folder.
            /// </summary>
            public ZangConnectGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ZangConnectGoogleChrome", "/form[@title~'^Zang\\ Connect\\ -\\ Google\\ Chr']", parentFolder, 30000, null, true, "8d16435a-b141-4d20-9065-d6d559156dc8", "")
            {
                _zangconnectforwebexInfo = new RepoItemInfo(this, "ZangConnectForWebEx", "container[@accessiblename='Google Chrome']//toolbar[@accessiblename='main']/?/?/button[@accessiblename='Zang Connect for WebEx' and @accessiblerole='PushButton']", 30000, null, "30deba7c-1878-4a65-a706-b90ebd30ba1d");
                _zangconnectforwebex1Info = new RepoItemInfo(this, "ZangConnectForWebEx1", "container[@accessiblename='Google Chrome']//toolbar[@accessiblename='main']/?/?/button[@accessiblename='Zang Connect for WebEx']", 30000, null, "2324ff59-ecfd-4469-93fe-4792779497b9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8d16435a-b141-4d20-9065-d6d559156dc8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8d16435a-b141-4d20-9065-d6d559156dc8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ZangConnectForWebEx item.
            /// </summary>
            [RepositoryItem("30deba7c-1878-4a65-a706-b90ebd30ba1d")]
            public virtual Ranorex.Button ZangConnectForWebEx
            {
                get
                {
                    return _zangconnectforwebexInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ZangConnectForWebEx item info.
            /// </summary>
            [RepositoryItemInfo("30deba7c-1878-4a65-a706-b90ebd30ba1d")]
            public virtual RepoItemInfo ZangConnectForWebExInfo
            {
                get
                {
                    return _zangconnectforwebexInfo;
                }
            }

            /// <summary>
            /// The ZangConnectForWebEx1 item.
            /// </summary>
            [RepositoryItem("2324ff59-ecfd-4469-93fe-4792779497b9")]
            public virtual Ranorex.Button ZangConnectForWebEx1
            {
                get
                {
                    return _zangconnectforwebex1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ZangConnectForWebEx1 item info.
            /// </summary>
            [RepositoryItemInfo("2324ff59-ecfd-4469-93fe-4792779497b9")]
            public virtual RepoItemInfo ZangConnectForWebEx1Info
            {
                get
                {
                    return _zangconnectforwebex1Info;
                }
            }
        }

        /// <summary>
        /// The ChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("9c4c7428-8c47-4a17-b67a-eff7de12bd9a")]
        public partial class ChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element216437072Info;
            RepoItemInfo _element309695888Info;

            /// <summary>
            /// Creates a new Chrome  folder.
            /// </summary>
            public ChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Chrome", "/form[@title='' and @processname='chrome']", parentFolder, 30000, null, true, "9c4c7428-8c47-4a17-b67a-eff7de12bd9a", "")
            {
                _element216437072Info = new RepoItemInfo(this, "Element216437072", "element[@controlid='216437072']", 30000, null, "4fe1e8fa-2676-478f-875b-47ecc41c1168");
                _element309695888Info = new RepoItemInfo(this, "Element309695888", "element[@controlid='309695888']", 30000, null, "057d3c5a-4fed-4b59-b8c9-147808f28106");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9c4c7428-8c47-4a17-b67a-eff7de12bd9a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9c4c7428-8c47-4a17-b67a-eff7de12bd9a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element216437072 item.
            /// </summary>
            [RepositoryItem("4fe1e8fa-2676-478f-875b-47ecc41c1168")]
            public virtual Ranorex.Unknown Element216437072
            {
                get
                {
                    return _element216437072Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element216437072 item info.
            /// </summary>
            [RepositoryItemInfo("4fe1e8fa-2676-478f-875b-47ecc41c1168")]
            public virtual RepoItemInfo Element216437072Info
            {
                get
                {
                    return _element216437072Info;
                }
            }

            /// <summary>
            /// The Element309695888 item.
            /// </summary>
            [RepositoryItem("057d3c5a-4fed-4b59-b8c9-147808f28106")]
            public virtual Ranorex.Unknown Element309695888
            {
                get
                {
                    return _element309695888Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element309695888 item info.
            /// </summary>
            [RepositoryItemInfo("057d3c5a-4fed-4b59-b8c9-147808f28106")]
            public virtual RepoItemInfo Element309695888Info
            {
                get
                {
                    return _element309695888Info;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("d6a7a029-e114-47e5-9070-c16335381b3d")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "d6a7a029-e114-47e5-9070-c16335381b3d", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d6a7a029-e114-47e5-9070-c16335381b3d")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d6a7a029-e114-47e5-9070-c16335381b3d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The CiscoWebExMeetingCenterAppFolder folder.
        /// </summary>
        [RepositoryFolder("2cc40ca8-7d17-4fd1-b171-d884a32500d7")]
        public partial class CiscoWebExMeetingCenterAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _webexmeetinghash111Info;
            RepoItemInfo _endmeetingInfo;
            RepoItemInfo _inviteandremindotherstojoinInfo;

            /// <summary>
            /// Creates a new CiscoWebExMeetingCenter  folder.
            /// </summary>
            public CiscoWebExMeetingCenterAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CiscoWebExMeetingCenter", "/form[@title~'^Cisco\\ WebEx\\ Meeting\\ Cente']", parentFolder, 30000, null, true, "2cc40ca8-7d17-4fd1-b171-d884a32500d7", "")
            {
                _webexmeetinghash111Info = new RepoItemInfo(this, "WebExMeetingHash111", "container[@caption='' and @accessiblerole='Client' and @accessibledescription='c1911']/container[@caption='' and @accessiblerole='Client' and @accessibledescription='c10314']/?/?/container[@accessiblename='Quick Start']//text[@accessiblerole='Text' and @accessibledescription='c1031']", 30000, null, "7ff9d328-ca8d-4376-918d-27d0383f6882");
                _endmeetingInfo = new RepoItemInfo(this, "EndMeeting", "container[@caption='' and @accessiblerole='Client' and @accessibledescription='c1911']//container[@accessiblename='Quick Start']//container[@caption='' and @accessiblerole='Client' and @accessibledescription='o7150']/button[@accessiblename='End Meeting']", 30000, null, "0a362e45-9745-4eeb-9cdf-aa294fd8568d");
                _inviteandremindotherstojoinInfo = new RepoItemInfo(this, "InviteAndRemindOthersToJoin", "container[@caption='' and @accessiblerole='Client' and @accessibledescription='c1911']//container[@accessiblename='Quick Start']/container[@caption='' and @accessiblerole='Client' and @accessibledescription='c1020']/?/?/button[@accessiblename~'^Invite\\ and\\ remind\\ others\\ ']", 30000, null, "e0c845ca-0d85-4dff-9945-27ac73b0d060");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2cc40ca8-7d17-4fd1-b171-d884a32500d7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2cc40ca8-7d17-4fd1-b171-d884a32500d7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WebExMeetingHash111 item.
            /// </summary>
            [RepositoryItem("7ff9d328-ca8d-4376-918d-27d0383f6882")]
            public virtual Ranorex.Text WebExMeetingHash111
            {
                get
                {
                    return _webexmeetinghash111Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The WebExMeetingHash111 item info.
            /// </summary>
            [RepositoryItemInfo("7ff9d328-ca8d-4376-918d-27d0383f6882")]
            public virtual RepoItemInfo WebExMeetingHash111Info
            {
                get
                {
                    return _webexmeetinghash111Info;
                }
            }

            /// <summary>
            /// The EndMeeting item.
            /// </summary>
            [RepositoryItem("0a362e45-9745-4eeb-9cdf-aa294fd8568d")]
            public virtual Ranorex.Button EndMeeting
            {
                get
                {
                    return _endmeetingInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EndMeeting item info.
            /// </summary>
            [RepositoryItemInfo("0a362e45-9745-4eeb-9cdf-aa294fd8568d")]
            public virtual RepoItemInfo EndMeetingInfo
            {
                get
                {
                    return _endmeetingInfo;
                }
            }

            /// <summary>
            /// The InviteAndRemindOthersToJoin item.
            /// </summary>
            [RepositoryItem("e0c845ca-0d85-4dff-9945-27ac73b0d060")]
            public virtual Ranorex.Button InviteAndRemindOthersToJoin
            {
                get
                {
                    return _inviteandremindotherstojoinInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The InviteAndRemindOthersToJoin item info.
            /// </summary>
            [RepositoryItemInfo("e0c845ca-0d85-4dff-9945-27ac73b0d060")]
            public virtual RepoItemInfo InviteAndRemindOthersToJoinInfo
            {
                get
                {
                    return _inviteandremindotherstojoinInfo;
                }
            }
        }

        /// <summary>
        /// The EndMeetingAppFolder folder.
        /// </summary>
        [RepositoryFolder("ba8edcfe-6fd4-451a-8e57-258f7a459b50")]
        public partial class EndMeetingAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _endmeetingInfo;

            /// <summary>
            /// Creates a new EndMeeting  folder.
            /// </summary>
            public EndMeetingAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EndMeeting", "/form[@title='End Meeting']", parentFolder, 30000, null, true, "ba8edcfe-6fd4-451a-8e57-258f7a459b50", "")
            {
                _endmeetingInfo = new RepoItemInfo(this, "EndMeeting", "?/?/button[@accessiblename='End Meeting']", 30000, null, "af190d90-af19-4b68-af01-62acdb30dc81");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ba8edcfe-6fd4-451a-8e57-258f7a459b50")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ba8edcfe-6fd4-451a-8e57-258f7a459b50")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EndMeeting item.
            /// </summary>
            [RepositoryItem("af190d90-af19-4b68-af01-62acdb30dc81")]
            public virtual Ranorex.Button EndMeeting
            {
                get
                {
                    return _endmeetingInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EndMeeting item info.
            /// </summary>
            [RepositoryItemInfo("af190d90-af19-4b68-af01-62acdb30dc81")]
            public virtual RepoItemInfo EndMeetingInfo
            {
                get
                {
                    return _endmeetingInfo;
                }
            }
        }

        /// <summary>
        /// The EsnaComCalendarWeekOfOctober2AppFolder folder.
        /// </summary>
        [RepositoryFolder("9eda9743-21b8-44e4-ba40-ea522f435255")]
        public partial class EsnaComCalendarWeekOfOctober2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _gw6zhcInfo;
            RepoItemInfo _j3nywInfo;
            RepoItemInfo _usx8odp86ukebz112cucxfnticoucxplgicoInfo;
            RepoItemInfo _webex0addtextInfo;
            CghhOe0InfoClass _cghhoe0Info;
            RepoItemInfo _webex0startInfo;
            RepoItemInfo _cghhoe1Info;
            CghhOe2InfoClass _cghhoe2Info;

            /// <summary>
            /// Creates a new EsnaComCalendarWeekOfOctober2  folder.
            /// </summary>
            public EsnaComCalendarWeekOfOctober2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("EsnaComCalendarWeekOfOctober2", "/dom[@domain='calendar.google.com']", parentFolder, 30000, null, false, "9eda9743-21b8-44e4-ba40-ea522f435255", "")
            {
                _gw6zhcInfo = new RepoItemInfo(this, "Gw6Zhc", ".//body[#'yDmH0d']/div[3]//i", 30000, null, "653372c6-a5f0-4601-b2c7-d3860698f0a3");
                _j3nywInfo = new RepoItemInfo(this, "J3nyw", ".//tag[#'tabEventDetails']/div[2]/div[2]", 30000, null, "dca1a61f-cbb4-47a5-bbe7-90f0aa14faa1");
                _usx8odp86ukebz112cucxfnticoucxplgicoInfo = new RepoItemInfo(this, "USx8OdP86ukeBz112cUcxFntIcoUcxPlgIco", ".//tag[#'tabEventDetails']/div[2]/div[1]/div", 30000, null, "5f1cdc7d-a8b6-419b-ba6d-46c2b5650ec0");
                _webex0addtextInfo = new RepoItemInfo(this, "Webex0addtext", ".//span[#'webex0addtext']", 30000, null, "06e7811f-df60-4929-900a-0df420b35dee");
                _cghhoe0Info = new CghhOe0InfoClass(this);
                _webex0startInfo = new RepoItemInfo(this, "Webex0start", ".//a[#'webex0start']", 30000, null, "582c348e-f4d8-45bc-bc0c-c13912a4e8a5");
                _cghhoe1Info = new RepoItemInfo(this, "CghhOe1", ".//div[#'CghhOe1']", 30000, null, "12296ed3-1ad7-4261-900a-0c6240301eff");
                _cghhoe2Info = new CghhOe2InfoClass(this);
            }

            /// <summary>
            /// The CghhOe0InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("1a6679af-96ff-4a8e-b75a-13407f2127c1")]
            public class CghhOe0InfoClass : RepoItemInfo
            {
                /// <summary>
                /// CghhOe0InfoClass class constructor.
                /// </summary>
                public CghhOe0InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "CghhOe0", ".//div[#'CghhOe0']", 30000, null, "1a6679af-96ff-4a8e-b75a-13407f2127c1")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("d753c9d8-15aa-428d-8798-e725844faa66")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("d753c9d8-15aa-428d-8798-e725844faa66");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("d753c9d8-15aa-428d-8798-e725844faa66")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("d753c9d8-15aa-428d-8798-e725844faa66", cropRect);
                }
            }

            /// <summary>
            /// The CghhOe2InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("5afdd211-7309-4b48-b40f-0c8c79c0db63")]
            public class CghhOe2InfoClass : RepoItemInfo
            {
                /// <summary>
                /// CghhOe2InfoClass class constructor.
                /// </summary>
                public CghhOe2InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "CghhOe2", ".//div[#'CghhOe2']", 30000, null, "5afdd211-7309-4b48-b40f-0c8c79c0db63")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("898999a5-caa5-49d8-bd53-e4c84805c718")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("898999a5-caa5-49d8-bd53-e4c84805c718");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("898999a5-caa5-49d8-bd53-e4c84805c718")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("898999a5-caa5-49d8-bd53-e4c84805c718", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9eda9743-21b8-44e4-ba40-ea522f435255")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9eda9743-21b8-44e4-ba40-ea522f435255")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Gw6Zhc item.
            /// </summary>
            [RepositoryItem("653372c6-a5f0-4601-b2c7-d3860698f0a3")]
            public virtual Ranorex.ITag Gw6Zhc
            {
                get
                {
                    return _gw6zhcInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The Gw6Zhc item info.
            /// </summary>
            [RepositoryItemInfo("653372c6-a5f0-4601-b2c7-d3860698f0a3")]
            public virtual RepoItemInfo Gw6ZhcInfo
            {
                get
                {
                    return _gw6zhcInfo;
                }
            }

            /// <summary>
            /// The J3nyw item.
            /// </summary>
            [RepositoryItem("dca1a61f-cbb4-47a5-bbe7-90f0aa14faa1")]
            public virtual Ranorex.DivTag J3nyw
            {
                get
                {
                    return _j3nywInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The J3nyw item info.
            /// </summary>
            [RepositoryItemInfo("dca1a61f-cbb4-47a5-bbe7-90f0aa14faa1")]
            public virtual RepoItemInfo J3nywInfo
            {
                get
                {
                    return _j3nywInfo;
                }
            }

            /// <summary>
            /// The USx8OdP86ukeBz112cUcxFntIcoUcxPlgIco item.
            /// </summary>
            [RepositoryItem("5f1cdc7d-a8b6-419b-ba6d-46c2b5650ec0")]
            public virtual Ranorex.DivTag USx8OdP86ukeBz112cUcxFntIcoUcxPlgIco
            {
                get
                {
                    return _usx8odp86ukebz112cucxfnticoucxplgicoInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The USx8OdP86ukeBz112cUcxFntIcoUcxPlgIco item info.
            /// </summary>
            [RepositoryItemInfo("5f1cdc7d-a8b6-419b-ba6d-46c2b5650ec0")]
            public virtual RepoItemInfo USx8OdP86ukeBz112cUcxFntIcoUcxPlgIcoInfo
            {
                get
                {
                    return _usx8odp86ukebz112cucxfnticoucxplgicoInfo;
                }
            }

            /// <summary>
            /// The Webex0addtext item.
            /// </summary>
            [RepositoryItem("06e7811f-df60-4929-900a-0df420b35dee")]
            public virtual Ranorex.SpanTag Webex0addtext
            {
                get
                {
                    return _webex0addtextInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Webex0addtext item info.
            /// </summary>
            [RepositoryItemInfo("06e7811f-df60-4929-900a-0df420b35dee")]
            public virtual RepoItemInfo Webex0addtextInfo
            {
                get
                {
                    return _webex0addtextInfo;
                }
            }

            /// <summary>
            /// The CghhOe0 item.
            /// </summary>
            [RepositoryItem("1a6679af-96ff-4a8e-b75a-13407f2127c1")]
            public virtual Ranorex.DivTag CghhOe0
            {
                get
                {
                    return _cghhoe0Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CghhOe0 item info.
            /// </summary>
            [RepositoryItemInfo("1a6679af-96ff-4a8e-b75a-13407f2127c1")]
            public virtual CghhOe0InfoClass CghhOe0Info
            {
                get
                {
                    return _cghhoe0Info;
                }
            }

            /// <summary>
            /// The Webex0start item.
            /// </summary>
            [RepositoryItem("582c348e-f4d8-45bc-bc0c-c13912a4e8a5")]
            public virtual Ranorex.ATag Webex0start
            {
                get
                {
                    return _webex0startInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Webex0start item info.
            /// </summary>
            [RepositoryItemInfo("582c348e-f4d8-45bc-bc0c-c13912a4e8a5")]
            public virtual RepoItemInfo Webex0startInfo
            {
                get
                {
                    return _webex0startInfo;
                }
            }

            /// <summary>
            /// The CghhOe1 item.
            /// </summary>
            [RepositoryItem("12296ed3-1ad7-4261-900a-0c6240301eff")]
            public virtual Ranorex.DivTag CghhOe1
            {
                get
                {
                    return _cghhoe1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CghhOe1 item info.
            /// </summary>
            [RepositoryItemInfo("12296ed3-1ad7-4261-900a-0c6240301eff")]
            public virtual RepoItemInfo CghhOe1Info
            {
                get
                {
                    return _cghhoe1Info;
                }
            }

            /// <summary>
            /// The CghhOe2 item.
            /// </summary>
            [RepositoryItem("5afdd211-7309-4b48-b40f-0c8c79c0db63")]
            public virtual Ranorex.DivTag CghhOe2
            {
                get
                {
                    return _cghhoe2Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CghhOe2 item info.
            /// </summary>
            [RepositoryItemInfo("5afdd211-7309-4b48-b40f-0c8c79c0db63")]
            public virtual CghhOe2InfoClass CghhOe2Info
            {
                get
                {
                    return _cghhoe2Info;
                }
            }
        }

        /// <summary>
        /// The AtmgrAppFolder folder.
        /// </summary>
        [RepositoryFolder("a8e1ec56-f657-48da-a99a-3ab7829a13a4")]
        public partial class AtmgrAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _skipInfo;
            RepoItemInfo _esnatechqcatgmailcomInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new Atmgr  folder.
            /// </summary>
            public AtmgrAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Atmgr", "/form[@title='' and @processname='atmgr']", parentFolder, 30000, null, true, "a8e1ec56-f657-48da-a99a-3ab7829a13a4", "")
            {
                _skipInfo = new RepoItemInfo(this, "Skip", ".//container[@caption='' and @accessiblerole='Client' and @accessibledescription='o17200']/button[@accessiblename='Skip']", 30000, null, "e9d2fd1c-060e-4999-91d9-eab6a4d8e135");
                _esnatechqcatgmailcomInfo = new RepoItemInfo(this, "EsnatechqcAtgmailCom", "container[@caption='' and @accessiblerole='Client' and @accessibledescription='c10016']//tree[@accessiblename='esnatechqc@gmail.com']/treeitem[@accessiblename='esnatechqc@gmail.com']", 30000, null, "f969cc3c-0a43-493c-bb03-3b5d1c058f6a");
                _closeInfo = new RepoItemInfo(this, "Close", "button[@accessiblename='Close']", 30000, null, "bc64cb8c-5cf5-45f5-999f-3962ed24b2b6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a8e1ec56-f657-48da-a99a-3ab7829a13a4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a8e1ec56-f657-48da-a99a-3ab7829a13a4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Skip item.
            /// </summary>
            [RepositoryItem("e9d2fd1c-060e-4999-91d9-eab6a4d8e135")]
            public virtual Ranorex.Button Skip
            {
                get
                {
                    return _skipInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Skip item info.
            /// </summary>
            [RepositoryItemInfo("e9d2fd1c-060e-4999-91d9-eab6a4d8e135")]
            public virtual RepoItemInfo SkipInfo
            {
                get
                {
                    return _skipInfo;
                }
            }

            /// <summary>
            /// The EsnatechqcAtgmailCom item.
            /// </summary>
            [RepositoryItem("f969cc3c-0a43-493c-bb03-3b5d1c058f6a")]
            public virtual Ranorex.TreeItem EsnatechqcAtgmailCom
            {
                get
                {
                    return _esnatechqcatgmailcomInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The EsnatechqcAtgmailCom item info.
            /// </summary>
            [RepositoryItemInfo("f969cc3c-0a43-493c-bb03-3b5d1c058f6a")]
            public virtual RepoItemInfo EsnatechqcAtgmailComInfo
            {
                get
                {
                    return _esnatechqcatgmailcomInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("bc64cb8c-5cf5-45f5-999f-3962ed24b2b6")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("bc64cb8c-5cf5-45f5-999f-3962ed24b2b6")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The ContactManagerMatheesanmAtesnaComAppFolder folder.
        /// </summary>
        [RepositoryFolder("edaff561-c490-4720-bb36-08ce2d71f26e")]
        public partial class ContactManagerMatheesanmAtesnaComAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _esnatechInfo;

            /// <summary>
            /// Creates a new ContactManagerMatheesanmAtesnaCom  folder.
            /// </summary>
            public ContactManagerMatheesanmAtesnaComAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ContactManagerMatheesanmAtesnaCom", "/dom[13]", parentFolder, 30000, null, false, "edaff561-c490-4720-bb36-08ce2d71f26e", "")
            {
                _esnatechInfo = new RepoItemInfo(this, "EsnaTech", ".//tr[#':2t']//span[@innertext='Esna Tech']", 30000, null, "ad738747-4f39-42f0-b9e3-578c03be4e9b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("edaff561-c490-4720-bb36-08ce2d71f26e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("edaff561-c490-4720-bb36-08ce2d71f26e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EsnaTech item.
            /// </summary>
            [RepositoryItem("ad738747-4f39-42f0-b9e3-578c03be4e9b")]
            public virtual Ranorex.SpanTag EsnaTech
            {
                get
                {
                    return _esnatechInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The EsnaTech item info.
            /// </summary>
            [RepositoryItemInfo("ad738747-4f39-42f0-b9e3-578c03be4e9b")]
            public virtual RepoItemInfo EsnaTechInfo
            {
                get
                {
                    return _esnatechInfo;
                }
            }
        }

        /// <summary>
        /// The ContactManagerMatheesanmAtesnaCom1AppFolder folder.
        /// </summary>
        [RepositoryFolder("057df526-6445-4918-979c-b660250e3989")]
        public partial class ContactManagerMatheesanmAtesnaCom1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _esnatechInfo;

            /// <summary>
            /// Creates a new ContactManagerMatheesanmAtesnaCom1  folder.
            /// </summary>
            public ContactManagerMatheesanmAtesnaCom1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("ContactManagerMatheesanmAtesnaCom1", "/dom[10]", parentFolder, 30000, null, false, "057df526-6445-4918-979c-b660250e3989", "")
            {
                _esnatechInfo = new RepoItemInfo(this, "EsnaTech", ".//tr[#':2t']//span[@innertext='Esna Tech']", 30000, null, "8b1b1150-b0f3-4740-89b9-5f273cc4d1f2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("057df526-6445-4918-979c-b660250e3989")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("057df526-6445-4918-979c-b660250e3989")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EsnaTech item.
            /// </summary>
            [RepositoryItem("8b1b1150-b0f3-4740-89b9-5f273cc4d1f2")]
            public virtual Ranorex.SpanTag EsnaTech
            {
                get
                {
                    return _esnatechInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The EsnaTech item info.
            /// </summary>
            [RepositoryItemInfo("8b1b1150-b0f3-4740-89b9-5f273cc4d1f2")]
            public virtual RepoItemInfo EsnaTechInfo
            {
                get
                {
                    return _esnatechInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}